---
title: "script"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# General Notes:
# Look at SES (all variables are famSES, famincome, finanindep, indSES, indincome, educ)
# Important (used) SES variables are famincome, indSES, indincome
# Use midpoints of groups for buckets, and convert all to USD with PPP
```



```{r}
# Meta-analysis data
#df <- read.csv("./std_pt1_data.csv")
#df <- read.csv("./std_pt1_df_11_15.csv")
#df <- read.csv("./std_pt1_df_8_4_21_manual.csv")
#df <- read.csv("./std_pt1_df_8_4_21_manual2.csv")
#df <- read.csv("./std_pt1_df_10_22_21.csv")
#df <- read.csv("./std_pt1_df_1_25_22.csv")
#df <- read.csv("./std_pt1_df_2_15_22.csv")
#df <- read.csv("./std_pt1_df_3_16_22.csv")
#df <- read.csv("./std_pt1_df_4_28_22.csv")
df <- read.csv("./std_pt1_df_5_16_22.csv")


df[1] <- NULL #removing a weird extra column from step 1
df[2] <- NULL #removing other weird column from edited standardizing

NROW(df)
#colnames(df)
head(df)
#df
```



```{r}
# GDP per capita, PPP, year, country
gdp <- read.csv("./GDP.csv", skip = 4)
head(gdp)
```



```{r}
# Get country from ethnicity

df$country = as.character(df$ethn)

df$country[df$country == "Other" |
                   df$country == "" |
                   df$country == "Taiwanese" |
                   df$country == "Asian" |
                   df$country == "Hispanic" |
                   df$country == "African and African American" |
                   df$country == "German + American" |
                   df$country == "Multiracial" |
                   df$country == "Eastern Europe" |
                   df$country == "Native Hawaiian and Pacific Islander" |
                   df$country == "East Asian and East Asian American" |
                   df$country == "European and Middle Eastern and North Africa" |
                   df$country == "Prefer not to answer" |
                   df$country == "Asian and Pacific Islander" |
                   df$country == "Asian and Asian American" |
                   df$country == "South Asian and South Asian American" |
                   df$country == "Southeast Asian and Southeast Asian American"] = "Not included"

df$country[df$country == "European American" |
                   df$country == "East Asian American" |
                   df$country == "Chinese American" |
                   df$country == "Latino American" |
                   df$country == "African American" |
                   df$country == "Asian American" |
                   df$country == "Native American" |
                   df$country == "American" |
                   df$country == "Korean American" |
                   df$country == "Japanese American" |
                   df$country == "Filipino American" |
                   df$country == "Vietnamese American" |
                   df$country == "South Asian American" |
                   df$country == "Mexican American" |
                   df$country == "Central American" |
                   df$country == "South American" |
                   df$country == "Persian American" |
                   df$country == "Taiwanese American" |
                   df$country == "Thai American" |
                   df$country == "Thai Chinese American" |
                   df$country == "Chinese Vietnamese American" |
                   df$country == "Japanese Chinese Filipino Hawaiian American"] = "United States"

df$country[df$country == "European Canadian" | 
                   df$country == "Canadian"] = "Canada"

df$country[df$country == "Mexican"] = "Mexico"

df$country[df$country == "Brazilian"] = "Brazil"

df$country[df$country == "Colombian"] = "Colombia"

df$country[df$country == "Peruvian"] = "Peru"

df$country[df$country == "Hong Kong Chinese"] = "Hong Kong SAR, China"

df$country[df$country == "Chinese"] = "China"

df$country[df$country == "Japanese"] = "Japan"

df$country[df$country == "Korean"] = "Korea, Rep."

df$country[df$country == "Singaporean"] = "Singapore"

df$country[df$country == "Vietnamese"] = "Vietnam"

df$country[df$country == "Indian"] = "India"

df$country[df$country == "Nepalese"] = "Nepal"

df$country[df$country == "Filipino"] = "Philippines"

df$country[df$country == "Sri Lankan"] = "Sri Lanka"

df$country[df$country == "East Asian" |
                   df$country == "Southeast Asian"] = "East Asia & Pacific"

df$country[df$country == "Pacific Islander"] = "Pacific island small states"

df$country[df$country == "South Asian"] = "South Asia"

df$country[df$country == "Australian"] = "Australia"

df$country[df$country == "New Zealander"] = "New Zealand"

df$country[df$country == "Malaysian"] = "Malaysia"

df$country[df$country == "British"] = "United Kingdom"

df$country[df$country == "French"] = "France"

df$country[df$country == "Dutch"] = "Netherlands"

df$country[df$country == "Belgian"] = "Belgium"

df$country[df$country == "German"] = "Germany"

df$country[df$country == "Italian"] = "Italy"

df$country[df$country == "Polish"] = "Poland"

df$country[df$country == "Swedish"] = "Sweden"

df$country[df$country == "Moldovian"] = "Moldova"

df$country[df$country == "Russian"] = "Russian Federation"

df$country[df$country == "Bulgarian"] = "Bulgaria"

df$country[df$country == "Turkish"] = "Turkey"

df$country[df$country == "Middle Eastern" |
                   df$country == "Middle Eastern and Arab"] = "Middle East & North Africa"

df$country[df$country == "Israeli"] = "Israel"

df$country[df$country == "Iranian"] = "Iran, Islamic Rep."

df$country[df$country == "Ghanaian"] = "Ghana"

df$country[df$country == "Mauritian"] = "Mauritius"

df$country[df$country == "Nigerian"] = "Nigeria"

df$country[df$country == "Ethiopian"] = "Ethiopia"

df$country[df$country == "Omani"] = "Oman"

df$country[df$country == "Carribean"] = "Latin America & Caribbean"

df$country[df$country == "Chinese Macau"] = "Macao SAR, China"

df$country[df$country == "Lebanese"] = "Lebanon"

df$country[df$country == "Bangladeshi"] = "Bangladesh"

df$country[df$country == "Guatemalan"] = "Guatemala"

df$country[df$country == "Pakistani"] = "Pakistan"

df$country[df$country == "Indonesian"] = "Indonesia"

df$country[df$country == "Thai"] = "Thailand"

unique(df$country)
```


```{r}
gdp_new <- gdp[, c(1, 45:65)]
colnames(gdp_new)[1] <- "country"
head(gdp_new)

df_final <- merge(df, gdp_new, by=c("country"), all.x=TRUE)
df_final$collected_year_new <- trunc(df_final$collected_year)
#df_final$collected_year_new[is.na(df_final$collected_year_new)] <- 0
head(df_final)
```



```{r}
# getting correct GDP per capita based on the year
df_final$year_GDP_per_capita <- NA
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2002", df_final$X2002, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2003", df_final$X2003, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2004", df_final$X2004, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2005", df_final$X2005, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2006", df_final$X2006, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2007", df_final$X2007, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2008", df_final$X2008, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2009", df_final$X2009, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2010", df_final$X2010, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2011", df_final$X2011, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2012", df_final$X2012, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2013", df_final$X2013, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2014", df_final$X2014, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2015", df_final$X2015, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2016", df_final$X2016, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2017", df_final$X2017, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2018", df_final$X2018, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2019", df_final$X2019, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- ifelse(df_final$collected_year_new == "2020", df_final$X2020, df_final$year_GDP_per_capita)
df_final$year_GDP_per_capita <- df_final$year_GDP_per_capita / 10000

```



```{r}
### indSES

## Create new variables indSES_new and ethn_new_indSES for analysis

# indSES studies with values:

# 2006 Tsai study1 (1 - 5)
# 2006 Tsai study2 (1 - 5)
# 2014 Koopman-Holm study2 (1 - 5)
# 2014 Koopman-Holm study3 (1 - 5)
# 2018 Bencharit study3 (1 - 5)
# 2018 Bencharit study4a (1 - 5)
# 2013 Scheibe study1 (1 - 5)
# 2016 Koc study1 (1 - 10)
# 2016 Tsai study3 (1 - 5)
# 2018 Koc Identity Integration study1 (1 - 10)
# Unpublished Yi study1 (1 - 10)

# Updated w/ 8_4_21 dataset
# 2019 Tsai study3 (1-5, 6 is NA)
# 2020 Koopmann-Holm 1 study1 (1-5, 6 is NA)
# 2020 Koopmann-Holm 1 study2 (1-5, 6 is NA)
# 2020 Koopmann-Holm 1 study3 (1-5, 6 is NA)
# 2020 Koopmann-Holm 2 study3 (1-5, 999 is NA)
# 2020 Park study3 (1-5, 6 is NA)
# 2020 Salvador study1 (1-10)
# 2020 Vishkin study2 (1-5)
# 2020 Vishkin study3 (1-5)


# Create new variables for analysis
df_final$indSES_new <- df_final$indSES

# Convert to numeric
df_final$indSES_new <- as.numeric(as.character(df_final$indSES_new))

# Standardize values 1-5 (2016 Koc study1, 2018 Koc Identity Integration study1, Unpublished Yi study1, 2020 Salvador study1)
df_final$indSES_new <- ifelse(df_final$paper_study == "2016 Koc study1", 1+4/9*(df_final$indSES_new-1), df_final$indSES_new)
df_final$indSES_new <- ifelse(df_final$paper_study == "2018 Koc Identity Integration study1", 1+4/9*(df_final$indSES_new-1), df_final$indSES_new)
df_final$indSES_new <- ifelse(df_final$paper_study == "Unpublished Yi study1", 1+4/9*(df_final$indSES_new-1), df_final$indSES_new)
df_final$indSES_new <- ifelse(df_final$paper_study == "2020 Salvador study1", 1+4/9*(df_final$indSES_new-1), df_final$indSES_new)
#unique(df_final$indSES_new)

# Convert appropriate values to NA (should be anything > 5)
df_final$indSES_new[df_final$indSES_new > 5] <- NA
#unique(df_final$indSES_new)



```



```{r}
# indincome studies with values (* indicates ones that are standardized/exist in the data):

# 2013 Koopman-Holm study2 (USD: 1 - 0-10,000; 2 - 10,001-20,000; 3 - 20,001-30,000; 4 - 30,001-40,000; 5 - 40,001-50,000; 6 - 50,001-75,000; 8 - 100,000+; 999 - idk)

#*** 2014 Koopman-Holm study2 (USD: 1 - 0-10,000; 2 - 10,001-20,000; 3 - 20,001-30,000; 4 - 30,001-40,000; 5 - 40,0001-50,000; 6 - 50,001-75,000; 7 - 75,001-100,000; 8 - 100,000+)

#*** 2014 Luong study1 (USD: 1 - 0-10,000; 2 - 10,000-19,999; 3 - 20,000-29,999; 4 - 30,000-39,999; 5 - 40,000-49,999; 6 - 50,000-59,999; 7 - 60,000-69,999; 8 - 70,000-79,999; 9 - 80,000-89,999; 10 - 90,000-99,999; 11 - 100,000+)

#*** 2014 Mannell study1 (Canadian dollars: 1 - 0-50,000; 2 - 50,000-99,999; 3 - 100,000+)

#*** 2016 Da Jiang FTP study1 - (unsure currency; 1 - 80,000; 2 - 80,001-160,000; 3 - 160,001-240,000; 4 - 240,001-320,000; 5 - 320,001-400,000; 6 - 400,001-600,000; 7 - 600,0001+) (0 is NA)

#*** 2016 Da Jiang FTP study3 - (HKD; 1 - 0-5,000; 2 - 5,000-10,000; 3 - 10,001-20,000; 4 - 20,001-30,000; 5 - 30,001+)

#*** 2016 Da Jiang LTP study11 - (unsure currency; 1 - 80,000; 2 - 80,001-160,000; 3 - 160,001-240,000; 4 - 240,001-320,000; 5 - 320,001-400,000; 6 - 400,001-600,000; 7 - 600,0001+) (0 is NA)

#*** 2016 Da Jiang LTP study2 - (HKD; 1 - 0-5,000; 2 - 5,000-10,000; 3 - 10,001-20,000; 4 - 20,001-30,000; 5 - 30,001+)

#*** 2016 Ito study1 (1 = under 1,999,999 yen, 2 = 2,000,000 yen - 3,999,999 yen, 3 = 4,000,000 yen - 5,999,999 yen, 4 = 6,000,000 yen - 7,999,999 yen, 5 = 8,000,000 yen - 9,999,999 yen, 6 = 10,000,000 yen - 11,999,999 yen, 7 = 12,000,000 yen - 14,999,999 yen, 8 = 15,000,000 yen - 19,999,999 yen, 9 = Over 20,000,000 yen, 10 = Don't know.)

#*** 2018 Bencharit study3 (1 - 9)

#*** 2018 Bencharit study4a (1 - 12)

#*** 2018 Ito study1 (Japanese yen: 0 - 0-2,500,00; 1 - 2,500,000-7,500,000; 2 - 7,500,000+)

#*** 2019 Palmer study1 (USD input)

#*** Unpublished Ito Kono study1 (1 = under 1,999,999 yen, 2 = 2,000,000 yen - 3,999,999 yen, 3 = 4,000,000 yen - 5,999,999 yen, 4 = 6,000,000 yen - 7,999,999 yen, 5 = 8,000,000 yen - 9,999,999 yen, 6 = 10,000,000 yen - 11,999,999 yen, 7 = 12,000,000 yen - 14,999,999 yen, 8 = 15,000,000 yen - 19,999,999 yen, 9 = Over 20,000,000 yen, 10 = Don't know.)



# Updated w/ 8_4_21 dataset

#*** 2019 Tsai study3 (USD; 1 - < 10k, 2 - 10,001-20k, 3 - 20,001-30k, 4 - 30,001-40k, 5 - 40,001-50k, 6 - 50,001-75k, 7 - 75,001-100k, 8 - >100k, 9 is NA)

#*** 2020 Koopmann-Holm 2 study3 (USD; 1 - < 10k, 2 - 10,001-20k, 3 - 20,001-30k, 4 - 30,001-40k, 5 - 40,001-50k, 6 - 50,001-75k, 7 - 75,001-100k, 8 - >100k, 999 is NA)

#*** 2020 Park study3 (USD; 1 - < 10k, 2 - 10,001-20k, 3 - 20,001-30k, 4 - 30,001-40k, 5 - 40,001-50k, 6 - 50,001-75k, 7 - 75,001-100k, 8 - >100k)


# Create new variable for analysis
df_final$indincome_new <- df_final$indincome


# Remove commas
df_final$indincome_new <- gsub(",","",df_final$indincome_new)

# Regex to just keep numbers and decimals
df_final$indincome_new <- unlist(sapply(regmatches(df_final$indincome_new, gregexpr("[[:digit:]]+\\.*[[:digit:]]*", df_final$indincome_new)), function(x) { ifelse(identical(character(0), x), NA, x)}))

# Convert to numeric
df_final$indincome_new <- as.numeric(as.character(df_final$indincome_new))

# Turning 0s into NA
df_final$indincome_new <- replace(df_final$indincome_new, df_final$indincome_new == 0, NA)

unique(df_final$indincome_new)

## Convert all to USD by PPP in 2015, use midpoints
## Data source here: https://data.worldbank.org/indicator/PA.NUS.PPP
Canada_convert <- 1.248042
China_convert <- 3.87069725990295
HK_convert <- 5.83105325698853
Japan_convert <- 103.469437

# Set a max multiplier - for things that are X_amount+ (e.g. $100,000+), set the value as multipler * X_amount
# So if we have a box of $100,000+ and the multipler is 2, then we would set the income as 200,000.
# max_mult <- 2
max_mult <- 1
# max_mult <- NA
```

```{r}
# Standardizing indincome values
# NOTE: Still missing 2018 Bencharit study 3 and 4a


#*** 2014 Koopman-Holm study2 (USD: 1 - 0-10,000; 2 - 10,001-20,000; 3 - 20,001-30,000; 4 - 30,001-40,000; 5 - 40,0001-50,000; 6 - 50,001-75,000; 7 - 75,001-100,000; 8 - 100,000+)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2014 Koopman-Holm study2"), 5000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2014 Koopman-Holm study2"), 15000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2014 Koopman-Holm study2"), 25000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2014 Koopman-Holm study2"), 35000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2014 Koopman-Holm study2"), 45000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2014 Koopman-Holm study2"), 62500, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2014 Koopman-Holm study2"), 87500, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 8 & df_final$paper_study == "2014 Koopman-Holm study2"), max_mult*100000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 9 & df_final$paper_study == "2014 Koopman-Holm study2"), NA, df_final$indincome_new)

#*** 2014 Luong study1 (USD: 1 - 0-10,000; 2 - 10,000-19,999; 3 - 20,000-29,999; 4 - 30,000-39,999; 5 - 40,000-49,999; 6 - 50,000-59,999; 7 - 60,000-69,999; 8 - 70,000-79,999; 9 - 80,000-89,999; 10 - 90,000-99,999; 11 - 100,000+)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2014 Luong study1"), 5000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2014 Luong study1"), 15000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2014 Luong study1"), 25000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2014 Luong study1"), 35000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2014 Luong study1"), 45000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2014 Luong study1"), 55000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2014 Luong study1"), 65000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 8 & df_final$paper_study == "2014 Luong study1"), 75000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 9 & df_final$paper_study == "2014 Luong study1"), 85000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 10 & df_final$paper_study == "2014 Luong study1"), 95000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 11 & df_final$paper_study == "2014 Luong study1"), max_mult*100000, df_final$indincome_new)

#*** 2014 Mannell study1 (Canadian dollars: 1 - 0-50,000; 2 - 50,000-99,999; 3 - 100,000+)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2014 Mannell study1"), 25000*(1/Canada_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2014 Mannell study1"), 75000*(1/Canada_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2014 Mannell study1"), max_mult*100000*(1/Canada_convert), df_final$indincome_new)

#*** 2016 Da Jiang FTP study1 - (unsure currency; 1 - 80,000; 2 - 80,001-160,000; 3 - 160,001-240,000; 4 - 240,001-320,000; 5 - 320,001-400,000; 6 - 400,001-600,000; 7 - 600,0001+) (0 is NA)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2016 Da Jiang FTP study1"), 40000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2016 Da Jiang FTP study1"), 120000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2016 Da Jiang FTP study1"), 200000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2016 Da Jiang FTP study1"), 280000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2016 Da Jiang FTP study1"), 360000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2016 Da Jiang FTP study1"), 500000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2016 Da Jiang FTP study1"), max_mult*600000*(1/HK_convert), df_final$indincome_new)

#*** 2016 Da Jiang FTP study3 - (HKD; 1 - 0-5,000; 2 - 5,000-10,000; 3 - 10,001-20,000; 4 - 20,001-30,000; 5 - 30,001+) - MONTHLY
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2016 Da Jiang FTP study3"), 2500*(1/HK_convert)*12, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2016 Da Jiang FTP study3"), 7500*(1/HK_convert)*12, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2016 Da Jiang FTP study3"), 15000*(1/HK_convert)*12, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2016 Da Jiang FTP study3"), 25000*(1/HK_convert)*12, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2016 Da Jiang FTP study3"), max_mult*30000*(1/HK_convert)*12, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2016 Da Jiang FTP study3"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2016 Da Jiang FTP study3"), NA, df_final$indincome_new)

#*** 2016 Da Jiang LTP study11 - (unsure currency; 1 - 80,000; 2 - 80,001-160,000; 3 - 160,001-240,000; 4 - 240,001-320,000; 5 - 320,001-400,000; 6 - 400,001-600,000; 7 - 600,0001+) (0 is NA)
df_final$indincome_new <- ifelse((df_final$indincome_new == 0 & df_final$paper_study == "2016 Da Jiang LTP study11"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2016 Da Jiang LTP study11"), 40000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2016 Da Jiang LTP study11"), 120000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2016 Da Jiang LTP study11"), 200000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2016 Da Jiang LTP study11"), 280000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2016 Da Jiang LTP study11"), 360000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2016 Da Jiang LTP study11"), 500000*(1/HK_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2016 Da Jiang LTP study11"), max_mult*600000*(1/HK_convert), df_final$indincome_new)

#*** 2016 Da Jiang LTP study2 - (HKD; 1 - 0-5,000; 2 - 5,000-10,000; 3 - 10,001-20,000; 4 - 20,001-30,000; 5 - 30,001+)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2016 Da Jiang LTP study2"), 2500*(1/HK_convert)*12, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2016 Da Jiang LTP study2"), 7500*(1/HK_convert)*12, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2016 Da Jiang LTP study2"), 15000*(1/HK_convert)*12, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2016 Da Jiang LTP study2"), 25000*(1/HK_convert)*12, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2016 Da Jiang LTP study2"), max_mult*30000*(1/HK_convert)*12, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2016 Da Jiang LTP study2"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2016 Da Jiang LTP study2"), NA, df_final$indincome_new)

#*** 2016 Ito study1 (1 = under 1,999,999 yen, 2 = 2,000,000 yen - 3,999,999 yen, 3 = 4,000,000 yen - 5,999,999 yen, 4 = 6,000,000 yen - 7,999,999 yen, 5 = 8,000,000 yen - 9,999,999 yen, 6 = 10,000,000 yen - 11,999,999 yen, 7 = 12,000,000 yen - 14,999,999 yen, 8 = 15,000,000 yen - 19,999,999 yen, 9 = Over 20,000,000 yen, 10 = Don't know.)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2016 Ito study1"), 1000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2016 Ito study1"), 3000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2016 Ito study1"), 5000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2016 Ito study1"), 7000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2016 Ito study1"), 9000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2016 Ito study1"), 11000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2016 Ito study1"), 13500000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 8 & df_final$paper_study == "2016 Ito study1"), 17500000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 9 & df_final$paper_study == "2016 Ito study1"), max_mult*20000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 10 & df_final$paper_study == "2016 Ito study1"), NA, df_final$indincome_new)

#*** 2018 Bencharit study3 (1 - 9)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2018 Bencharit study3"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2018 Bencharit study3"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2018 Bencharit study3"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2018 Bencharit study3"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2018 Bencharit study3"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2018 Bencharit study3"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2018 Bencharit study3"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 8 & df_final$paper_study == "2018 Bencharit study3"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 9 & df_final$paper_study == "2018 Bencharit study3"), NA, df_final$indincome_new)

#*** 2018 Bencharit study4a (1 - 12)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 8 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 9 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 10 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 11 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 12 & df_final$paper_study == "2018 Bencharit study4a"), NA, df_final$indincome_new)

#*** 2018 Ito study1 (Japanese yen: 0 - 0-2,500,000; 1 - 2,500,000-7,500,000; 2 - 7,500,000+)
df_final$indincome_new <- ifelse((df_final$indincome_new == 0 & df_final$paper_study == "2018 Ito study1"), (1/Japan_convert)*1250000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2018 Ito study1"), (1/Japan_convert)*5000000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2018 Ito study1"), (1/Japan_convert)*max_mult*7500000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2018 Ito study1"), NA, df_final$indincome_new)

#*** 2019 Palmer study1 (USD input)
df_final$indincome_new <- ifelse((df_final$indincome_new < 10000 & df_final$paper_study == "2019 Palmer study1"), NA, df_final$indincome_new)

#*** 2019 Tsai study3 (USD; 1 - < 10k, 2 - 10,001-20k, 3 - 20,001-30k, 4 - 30,001-40k, 5 - 40,001-50k, 6 - 50,001-75k, 7 - 75,001-100k, 8 - >100k, 9 is NA)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2019 Tsai study3"), 5000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2019 Tsai study3"), 15000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2019 Tsai study3"), 25000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2019 Tsai study3"), 35000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2019 Tsai study3"), 45000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2019 Tsai study3"), 62500, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2019 Tsai study3"), 87500, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 8 & df_final$paper_study == "2019 Tsai study3"), max_mult*100000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 9 & df_final$paper_study == "2019 Tsai study3"), NA, df_final$indincome_new)

#*** 2020 Koopmann-Holm 2 study3 (USD; 1 - < 10k, 2 - 10,001-20k, 3 - 20,001-30k, 4 - 30,001-40k, 5 - 40,001-50k, 6 - 50,001-75k, 7 - 75,001-100k, 8 - >100k, 999 is NA)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 5000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 15000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 25000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 35000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 45000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 62500, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 87500, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 8 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), max_mult*100000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 999 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), NA, df_final$indincome_new)

#*** 2020 Park study3 (USD; 1 - < 10k, 2 - 10,001-20k, 3 - 20,001-30k, 4 - 30,001-40k, 5 - 40,001-50k, 6 - 50,001-75k, 7 - 75,001-100k, 8 - >100k)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "2020 Park study3"), 5000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "2020 Park study3"), 15000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "2020 Park study3"), 25000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "2020 Park study3"), 35000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "2020 Park study3"), 45000, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "2020 Park study3"), 62500, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "2020 Park study3"), 87500, df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 8 & df_final$paper_study == "2020 Park study3"), max_mult*100000, df_final$indincome_new)

#*** Unpublished Ito Kono study1 (1 = under 1,999,999 yen, 2 = 2,000,000 yen - 3,999,999 yen, 3 = 4,000,000 yen - 5,999,999 yen, 4 = 6,000,000 yen - 7,999,999 yen, 5 = 8,000,000 yen - 9,999,999 yen, 6 = 10,000,000 yen - 11,999,999 yen, 7 = 12,000,000 yen - 14,999,999 yen, 8 = 15,000,000 yen - 19,999,999 yen, 9 = Over 20,000,000 yen, 10 = Don't know.)
df_final$indincome_new <- ifelse((df_final$indincome_new == 1 & df_final$paper_study == "Unpublished Ito Kono study1"), 1000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 2 & df_final$paper_study == "Unpublished Ito Kono study1"), 3000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 3 & df_final$paper_study == "Unpublished Ito Kono study1"), 5000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 4 & df_final$paper_study == "Unpublished Ito Kono study1"), 7000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 5 & df_final$paper_study == "Unpublished Ito Kono study1"), 9000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 6 & df_final$paper_study == "Unpublished Ito Kono study1"), 11000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 7 & df_final$paper_study == "Unpublished Ito Kono study1"), 13500000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 8 & df_final$paper_study == "Unpublished Ito Kono study1"), 17500000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 9 & df_final$paper_study == "Unpublished Ito Kono study1"), max_mult*20000000*(1/Japan_convert), df_final$indincome_new)
df_final$indincome_new <- ifelse((df_final$indincome_new == 10 & df_final$paper_study == "Unpublished Ito Kono study1"), NA, df_final$indincome_new)
```


```{r}
### famincome

# famincome studies with respective values:

# 2013 Koopman-Holm study2 (USD: 1 - 0-10,000; 2 - 10,001-20,000; 3 - 20,001-30,000; 4 - 30,001-40,000; 5 - 40,001-50,000; 6 - 50,001-75,000; 8 - 100,000+; 999 - idk)

#*** 2014 Koopman-Holm study2 (USD: 1 - 0-10,000; 2 - 10,001-20,000; 3 - 20,001-30,000; 4 - 30,001-40,000; 5 - 40,001-50,000; 6 - 50,001-75,000; 8 - 100,000+; 999 - idk)

#*** 2014 Mortazavi study1 (USD: 1 - 0-15k; 2 - 15-30k; 3 - 30-45k; 4 - 45-60k; 5 - 60-75k; 6 - 75k+; 7 - Prefer not to answer)

#*** 2016 Da Jiang FTP study1 - (unsure currency; 1 - 80,000; 2 - 80,001-160,000; 3 - 160,001-240,000; 4 - 240,001-320,000; 5 - 320,001-400,000; 6 - 400,001-600,000; 7 - 600,0001+)

#*** 2016 Da Jiang FTP study3 - (HKD; 1 - 0-5,000; 2 - 5,000-10,000; 3 - 10,001-20,000; 4 - 20,001-30,000; 5 - 30,001+)

#*** 2016 Da Jiang LTP study11 - (Unknown currency, maybe yuan; 1 - 80,000; 2 - 80,001-160,000; 3 - 160,001-240,000; 4 - 240,001-320,000; 5 - 320,001-400,000; 6 - 400,001-600,000; 7 - 600,0001+)

#*** 2016 Da Jiang LTP study2 - (HKD; 1 - 0-5,000; 2 - 5,000-10,000; 3 - 10,001-20,000; 4 - 20,001-30,000; 5 - 30,001+)

#*** 2016 Ito study1 (1 = under 1,999,999 yen, 2 = 2,000,000 yen - 3,999,999 yen, 3 = 4,000,000 yen - 5,999,999 yen, 4 = 6,000,000 yen - 7,999,999 yen, 5 = 8,000,000 yen - 9,999,999 yen, 6 = 10,000,000 yen - 11,999,999 yen, 7 = 12,000,000 yen - 14,999,999 yen, 8 = 15,000,000 yen - 19,999,999 yen, 9 = Over 20,000,000 yen, 10 = Don't know.)

#*** 2017 Oosterhoff study1 (USD: 1 - 0-11,999; 2 - 12,000-24,999; 3 - 25,000-49,999; 4 - 50,000-74,999; 5 - 75,000-99,999; 6 - 100,000-149,999; 7 - 150,000+; 8 - Prefer not to answer)

#*** 2018 Gentzler (USD: 1 - 0-10,000; 2 - 10,000-20,000; 3 - 20,000-30,000; 4 - 30,000-40,000; 5 - 40,000-50,000; 6 - 50,000-60,000; 7 - 60,000-70,000; 8 - 70,000-80,000; 9 - 80,000-90,000; 10 - 90,000-100,000; 11 - 100,000-150,000; 12 - 150,000+)

#*** 2018 Swerdlow study2 (USD: 1 - 0-10,000; 2 - 10,001-15,000; 3 - 15,001-25,000; 4 - 25,001-50,000; 5 - 50,001-75,000; 6 - 75,001-100,000; 7 - 100,001-150,000; 8 - 150,000+; 9 - idk)

#*** 2018 Tompson study1 (USD: 1=<40K, 2=40K-60K, 3=60K-80K, 4=80K-100K, 5=100K-120K, 6=120K-140K, 7=140K-160K, 8=>$60K)

#*** 2019 Palmer study1 (USD input)

#*** Unpublished Ito Kono study1 (1 = under 1,999,999 yen, 2 = 2,000,000 yen - 3,999,999 yen, 3 = 4,000,000 yen - 5,999,999 yen, 4 = 6,000,000 yen - 7,999,999 yen, 5 = 8,000,000 yen - 9,999,999 yen, 6 = 10,000,000 yen - 11,999,999 yen, 7 = 12,000,000 yen - 14,999,999 yen, 8 = 15,000,000 yen - 19,999,999 yen, 9 = Over 20,000,000 yen, 10 = Don't know.)

#*** Unpublished Ito Mika study1 (Yen: 1 - 0-2,500,000; 2 - 2,500,000-5,000,000; 3 - 5,000,000-7,500,000; 4 - 7,500,000-10,000,000; 5 - 10,000,000+; 6 - NA)

#*** Unpublished Ito Yamaguchi Takamatsu study1 (Yen: 1 - 0-2,500,000; 2 - 2,500,000-5,000,000; 3 - 5,000,000-7,500,000; 4 - 7,500,000-10,000,000; 5 - 10,000,000+; 6 - NA)

#*** Unpublished Palmer study1 (USD: 1 - 0-10,000; 2 - 10,000-20,000; 3 - 20,000-40,000; 4 - 40,000-60,000; 5 - 60,000-80,000; 6 - 80,000-100,000; 7 - 100-000+)


# Updated w/ 8_4_21 dataset

#*** 2020 Koopmann-Holm 2 study3 (USD; 1 - < 10k, 2 - 10,001-20k, 3 - 20,001-30k, 4 - 30,001-40k, 5 - 40,001-50k, 6 - 50,001-75k, 7 - 75,001-100k, 8 - >100k, 999 is NA)

#*** 2020 Park study3 (USD; 1 - < 10k, 2 - 10,001-20k, 3 - 20,001-30k, 4 - 30,001-40k, 5 - 40,001-50k, 6 - 50,001-75k, 7 - 75,001-100k, 8 - >100k)

#*** Unpublished Fung study1 (HKD; 1 - 0-10,000; 2 - 10,001-20,000; 3 - 20,001-30,000; 4 - 30,001-40,000; 5 - 40,001-50,000, 6->50,000)

#*** Unpublished Ito study1 (Yen: 1 - 0-2,500,000; 2 - 2,500,000-5,000,000; 3 - 5,000,000-7,500,000; 4 - 7,500,000-10,000,000; 5 - 10,000,000+; 6 - NA)

#*** Unpublished Samanez-Larkin agerl study1 - existing strings: Less than $10,000, $10,000-$19,999, $20,000-$29,999, $30,000-$39,999, $40,000-$49,999, $50,000-$59,999, $60,000-$69,999, $70,000-$79,999, $80,000-$89,999, $90,000-$99,999, $120,000-$129,999, $130,000-$139,999, $140,000-$149,999, $150,000 or more
#Note that the regex truncates the buckets for Unpublished Samanez-Larkin agerl study1 to the first number found, so the two 10k buckets must be combined


# Create new variable for analysis
df_final$famincome_new <- df_final$famincome


# Remove commas
df_final$famincome_new <- gsub(",","",df_final$famincome_new)

# Regex to just keep numbers and decimals
df_final$famincome_new <- unlist(sapply(regmatches(df_final$famincome_new, gregexpr("[[:digit:]]+\\.*[[:digit:]]*", df_final$famincome_new)), function(x) { ifelse(identical(character(0), x), NA, x)}))
#unique(sort(as.numeric(df_final[df_final$paper_study=="Unpublished Samanez-Larkin agerl study1",]$famincome_new))) #Note that this regex truncates the buckets for Unpublished Samanez-Larkin agerl study1 to the first number found

# Convert to numeric
df_final$famincome_new <- as.numeric(as.character(df_final$famincome_new))

# Turning 0s into NA
df_final$famincome_new <- replace(df_final$famincome_new, df_final$famincome_new == 0, NA)

unique(sort(df_final$famincome_new))

```

```{r}
# Standardizing famincome values


#*** 2014 Koopman-Holm study2 (USD: 1 - 0-10,000; 2 - 10,001-20,000; 3 - 20,001-30,000; 4 - 30,001-40,000; 5 - 40,001-50,000; 6 - 50,001-75,000; 8 - 100,000+; 999 - idk)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2014 Koopman-Holm study2"), 5000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2014 Koopman-Holm study2"), 15000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2014 Koopman-Holm study2"), 25000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2014 Koopman-Holm study2"), 35000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2014 Koopman-Holm study2"), 45000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2014 Koopman-Holm study2"), 62500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2014 Koopman-Holm study2"), 87500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 8 & df_final$paper_study == "2014 Koopman-Holm study2"), max_mult*100000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 9 & df_final$paper_study == "2014 Koopman-Holm study2"), NA, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 999 & df_final$paper_study == "2014 Koopman-Holm study2"), NA, df_final$famincome_new)

#*** 2014 Mortazavi study1 (USD: 1 - 0-15k; 2 - 15-30k; 3 - 30-45k; 4 - 45-60k; 5 - 60-75k; 6 - 75k+; 7 - Prefer not to answer)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2014 Mortazavi study1"), 7500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2014 Mortazavi study1"), 22500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2014 Mortazavi study1"), 37500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2014 Mortazavi study1"), 52500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2014 Mortazavi study1"), 67500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2014 Mortazavi study1"), max_mult*75000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2014 Mortazavi study1"), NA, df_final$famincome_new)

#*** 2016 Da Jiang FTP study1 - (unsure currency; 1 - 80,000; 2 - 80,001-160,000; 3 - 160,001-240,000; 4 - 240,001-320,000; 5 - 320,001-400,000; 6 - 400,001-600,000; 7 - 600,0001+)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2016 Da Jiang FTP study1"), 40000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2016 Da Jiang FTP study1"), 120000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2016 Da Jiang FTP study1"), 200000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2016 Da Jiang FTP study1"), 280000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2016 Da Jiang FTP study1"), 360000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2016 Da Jiang FTP study1"), 500000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2016 Da Jiang FTP study1"), max_mult*600000*(1/HK_convert), df_final$famincome_new)

#*** 2016 Da Jiang FTP study3 - (HKD; 1 - 0-5,000; 2 - 5,000-10,000; 3 - 10,001-20,000; 4 - 20,001-30,000; 5 - 30,001+) - MONTHLY
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2016 Da Jiang FTP study3"), 2500*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2016 Da Jiang FTP study3"), 7500*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2016 Da Jiang FTP study3"), 15000*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2016 Da Jiang FTP study3"), 25000*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2016 Da Jiang FTP study3"), max_mult*30000*(1/HK_convert)*12, df_final$famincome_new)

#*** 2016 Da Jiang LTP study11 - (Unknown currency, maybe yuan; 1 - 80,000; 2 - 80,001-160,000; 3 - 160,001-240,000; 4 - 240,001-320,000; 5 - 320,001-400,000; 6 - 400,001-600,000; 7 - 600,0001+)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2016 Da Jiang LTP study11"), 40000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2016 Da Jiang LTP study11"), 120000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2016 Da Jiang LTP study11"), 200000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2016 Da Jiang LTP study11"), 280000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2016 Da Jiang LTP study11"), 360000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2016 Da Jiang LTP study11"), 500000*(1/HK_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2016 Da Jiang LTP study11"), max_mult*600000*(1/HK_convert), df_final$famincome_new)

#*** 2016 Da Jiang LTP study2 - (HKD; 1 - 0-5,000; 2 - 5,000-10,000; 3 - 10,001-20,000; 4 - 20,001-30,000; 5 - 30,001+) - MONTHLY
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2016 Da Jiang LTP study2"), 2500*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2016 Da Jiang LTP study2"), 7500*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2016 Da Jiang LTP study2"), 15000*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2016 Da Jiang LTP study2"), 25000*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2016 Da Jiang LTP study2"), max_mult*30000*(1/HK_convert)*12, df_final$famincome_new)

#*** 2016 Ito study1 (1 = under 1,999,999 yen, 2 = 2,000,000 yen - 3,999,999 yen, 3 = 4,000,000 yen - 5,999,999 yen, 4 = 6,000,000 yen - 7,999,999 yen, 5 = 8,000,000 yen - 9,999,999 yen, 6 = 10,000,000 yen - 11,999,999 yen, 7 = 12,000,000 yen - 14,999,999 yen, 8 = 15,000,000 yen - 19,999,999 yen, 9 = Over 20,000,000 yen, 10 = Don't know.)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2016 Ito study1"), 1000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2016 Ito study1"), 3000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2016 Ito study1"), 5000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2016 Ito study1"), 7000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2016 Ito study1"), 9000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2016 Ito study1"), 11000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2016 Ito study1"), 13500000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 8 & df_final$paper_study == "2016 Ito study1"), 17500000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 9 & df_final$paper_study == "2016 Ito study1"), max_mult*20000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 10 & df_final$paper_study == "2016 Ito study1"), NA, df_final$famincome_new)

#*** 2017 Oosterhoff study1 (USD: 1 - 0-11,999; 2 - 12,000-24,999; 3 - 25,000-49,999; 4 - 50,000-74,999; 5 - 75,000-99,999; 6 - 100,000-149,999; 7 - 150,000+; 8 - Prefer not to answer)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2017 Oosterhoff study1"), 6000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2017 Oosterhoff study1"), 18500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2017 Oosterhoff study1"), 37500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2017 Oosterhoff study1"), 62500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2017 Oosterhoff study1"), 87500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2017 Oosterhoff study1"), 125000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2017 Oosterhoff study1"), max_mult*150000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 8 & df_final$paper_study == "2017 Oosterhoff study1"), NA, df_final$famincome_new)

#*** 2018 Gentzler (USD: 1 - 0-10,000; 2 - 10,000-20,000; 3 - 20,000-30,000; 4 - 30,000-40,000; 5 - 40,000-50,000; 6 - 50,000-60,000; 7 - 60,000-70,000; 8 - 70,000-80,000; 9 - 80,000-90,000; 10 - 90,000-100,000; 11 - 100,000-150,000; 12 - 150,000+)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2018 Gentzler study1"), 5000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2018 Gentzler study1"), 15000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2018 Gentzler study1"), 25000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2018 Gentzler study1"), 35000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2018 Gentzler study1"), 45000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2018 Gentzler study1"), 55000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2018 Gentzler study1"), 65000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 8 & df_final$paper_study == "2018 Gentzler study1"), 75000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 9 & df_final$paper_study == "2018 Gentzler study1"), 85000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 10 & df_final$paper_study == "2018 Gentzler study1"), 95000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 11 & df_final$paper_study == "2018 Gentzler study1"), 125000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 12 & df_final$paper_study == "2018 Gentzler study1"), max_mult*150000, df_final$famincome_new)

#*** 2018 Swerdlow study2 (USD: 1 - 0-10,000; 2 - 10,001-15,000; 3 - 15,001-25,000; 4 - 25,001-50,000; 5 - 50,001-75,000; 6 - 75,001-100,000; 7 - 100,001-150,000; 8 - 150,000+; 9 - idk)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2018 Swerdlow study2"), 5000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2018 Swerdlow study2"), 12500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2018 Swerdlow study2"), 20000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2018 Swerdlow study2"), 37500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2018 Swerdlow study2"), 62500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2018 Swerdlow study2"), 87500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2018 Swerdlow study2"), 125000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 8 & df_final$paper_study == "2018 Swerdlow study2"), max_mult*150000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 9 & df_final$paper_study == "2018 Swerdlow study2"), NA, df_final$famincome_new)

#*** 2018 Tompson study1 (USD: 1=<40K, 2=40K-60K, 3=60K-80K, 4=80K-100K, 5=100K-120K, 6=120K-140K, 7=140K-160K, 8=>$60K)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2018 Tompson study1"), 20000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2018 Tompson study1"), 50000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2018 Tompson study1"), 70000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2018 Tompson study1"), 90000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2018 Tompson study1"), 110000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2018 Tompson study1"), 130000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2018 Tompson study1"), 150000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 8 & df_final$paper_study == "2018 Tompson study1"), max_mult*160000, df_final$famincome_new)

#*** 2019 Palmer study1 (USD input)
df_final$famincome_new <- ifelse((df_final$famincome_new < 10000 & df_final$paper_study == "2019 Palmer study1"), NA, df_final$famincome_new)

#*** 2020 Koopmann-Holm 2 study3 (USD; 1 - < 10k, 2 - 10,001-20k, 3 - 20,001-30k, 4 - 30,001-40k, 5 - 40,001-50k, 6 - 50,001-75k, 7 - 75,001-100k, 8 - >100k, 999 is NA)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 5000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 15000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 25000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 35000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 45000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 62500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), 87500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 8 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), max_mult*100000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 9 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), NA, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 999 & df_final$paper_study == "2020 Koopmann-Holm 2 study3"), NA, df_final$famincome_new)

#*** 2020 Park study3 (USD; 1 - < 10k, 2 - 10,001-20k, 3 - 20,001-30k, 4 - 30,001-40k, 5 - 40,001-50k, 6 - 50,001-75k, 7 - 75,001-100k, 8 - >100k)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "2020 Park study3"), 5000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "2020 Park study3"), 15000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "2020 Park study3"), 25000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "2020 Park study3"), 35000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "2020 Park study3"), 45000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "2020 Park study3"), 62500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "2020 Park study3"), 87500, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 8 & df_final$paper_study == "2020 Park study3"), max_mult*100000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 9 & df_final$paper_study == "2020 Park study3"), NA, df_final$famincome_new)

#*** Unpublished Fung study1 (HKD; 1 - 0-10,000; 2 - 10,001-20,000; 3 - 20,001-30,000; 4 - 30,001-40,000; 5 - 40,001-50,000, 6->50,000) - Monthly?
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "Unpublished Fung study1"), 5000*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "Unpublished Fung study1"), 15000*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "Unpublished Fung study1"), 25000*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "Unpublished Fung study1"), 35000*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "Unpublished Fung study1"), 45000*(1/HK_convert)*12, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "Unpublished Fung study1"), max_mult*50000*(1/HK_convert)*12, df_final$famincome_new)

#*** Unpublished Ito Kono study1 (1 = under 1,999,999 yen, 2 = 2,000,000 yen - 3,999,999 yen, 3 = 4,000,000 yen - 5,999,999 yen, 4 = 6,000,000 yen - 7,999,999 yen, 5 = 8,000,000 yen - 9,999,999 yen, 6 = 10,000,000 yen - 11,999,999 yen, 7 = 12,000,000 yen - 14,999,999 yen, 8 = 15,000,000 yen - 19,999,999 yen, 9 = Over 20,000,000 yen, 10 = Don't know.)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "Unpublished Ito Kono study1"), 1000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "Unpublished Ito Kono study1"), 3000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "Unpublished Ito Kono study1"), 5000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "Unpublished Ito Kono study1"), 7000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "Unpublished Ito Kono study1"), 9000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "Unpublished Ito Kono study1"), 11000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "Unpublished Ito Kono study1"), 13500000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 8 & df_final$paper_study == "Unpublished Ito Kono study1"), 17500000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 9 & df_final$paper_study == "Unpublished Ito Kono study1"), max_mult*20000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 10 & df_final$paper_study == "Unpublished Ito Kono study1"), NA, df_final$famincome_new)

#*** Unpublished Ito Mika study1 (Yen: 1 - 0-2,500,000; 2 - 2,500,000-5,000,000; 3 - 5,000,000-7,500,000; 4 - 7,500,000-10,000,000; 5 - 10,000,000+; 6 - NA)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "Unpublished Ito Mika study1"), 1250000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "Unpublished Ito Mika study1"), 3750000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "Unpublished Ito Mika study1"), 6250000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "Unpublished Ito Mika study1"), 8750000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "Unpublished Ito Mika study1"), max_mult*10000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "Unpublished Ito Mika study1"), NA, df_final$famincome_new)

#*** Unpublished Ito Yamaguchi Takamatsu study1 (Yen: 1 - 0-2,500,000; 2 - 2,500,000-5,000,000; 3 - 5,000,000-7,500,000; 4 - 7,500,000-10,000,000; 5 - 10,000,000+; 6 - NA)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "Unpublished Ito Yamaguchi Takamatsu study1"), 1250000*1/(Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "Unpublished Ito Yamaguchi Takamatsu study1"), 3750000*1/(Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "Unpublished Ito Yamaguchi Takamatsu study1"), 6250000*1/(Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "Unpublished Ito Yamaguchi Takamatsu study1"), 8750000*1/(Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "Unpublished Ito Yamaguchi Takamatsu study1"), 20000000*1/(Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "Unpublished Ito Yamaguchi Takamatsu study1"), NA, df_final$famincome_new)

#*** Unpublished Ito study1 (Yen: 1 - 0-2,500,000; 2 - 2,500,000-5,000,000; 3 - 5,000,000-7,500,000; 4 - 7,500,000-10,000,000; 5 - 10,000,000+; 6 - NA)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "Unpublished Ito study1"), 1250000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "Unpublished Ito study1"), 3750000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "Unpublished Ito study1"), 6250000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "Unpublished Ito study1"), 8750000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "Unpublished Ito study1"), max_mult*10000000*(1/Japan_convert), df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "Unpublished Ito study1"), NA, df_final$famincome_new)

#*** Unpublished Palmer study1 (USD: 1 - 0-10,000; 2 - 10,000-20,000; 3 - 20,000-40,000; 4 - 40,000-60,000; 5 - 60,000-80,000; 6 - 80,000-100,000; 7 - 100-000+)
df_final$famincome_new <- ifelse((df_final$famincome_new == 1 & df_final$paper_study == "Unpublished Palmer study1"), 5000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 2 & df_final$paper_study == "Unpublished Palmer study1"), 15000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 3 & df_final$paper_study == "Unpublished Palmer study1"), 30000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 4 & df_final$paper_study == "Unpublished Palmer study1"), 50000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 5 & df_final$paper_study == "Unpublished Palmer study1"), 70000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 6 & df_final$paper_study == "Unpublished Palmer study1"), 90000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 7 & df_final$paper_study == "Unpublished Palmer study1"), max_mult*100000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 8 & df_final$paper_study == "Unpublished Palmer study1"), NA, df_final$famincome_new)

#*** Unpublished Samanez-Larkin agerl study1 - existing strings: Less than $10,000, $10,000-$19,999, $20,000-$29,999, $30,000-$39,999, $40,000-$49,999, $50,000-$59,999, $60,000-$69,999, $70,000-$79,999, $80,000-$89,999, $90,000-$99,999, $120,000-$129,999, $130,000-$139,999, $140,000-$149,999, $150,000 or more
#Note that the regex truncates the buckets for Unpublished Samanez-Larkin agerl study1 to the first number found, so the two 10k buckets must be combined
# New buckets are:  10000  20000  30000  40000  50000  60000  70000  80000  90000 120000 130000 140000 150000
df_final$famincome_new <- ifelse((df_final$famincome_new == 10000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 10000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 20000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 25000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 30000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 35000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 40000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 45000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 50000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 55000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 60000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 65000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 70000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 75000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 80000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 85000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 90000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 95000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 120000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 125000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 130000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 135000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 140000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), 145000, df_final$famincome_new)
df_final$famincome_new <- ifelse((df_final$famincome_new == 150000 & df_final$paper_study == "Unpublished Samanez-Larkin agerl study1"), max_mult*150000, df_final$famincome_new)


```


```{r}
df_final <- df_final[order(df_final$"Unnamed..0"), ]
write.csv(df_final, "std_pt2_df_5_16_22.csv", row.names = FALSE, na="")
```